[build]
  publish = "src/public"

[functions]
  directory = "netlify/functions"

[dev]
  publish = "src/public"
  functions = "netlify/functions"
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200